### ISSUE TITLE
Cannot resolve module "q"

### ISSUE THREAD

**Issue by afshin-hoseini** [backtory/backtory-local-node#1]
When I run _sude node api.js_ I encounter this problem:

>Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/afshinhoseini/Projects/TinyPro/Inkare/inkare/api/controller.js:8:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Would you please help me solve this problem?

**Comment by afshin-hoseini** [comment]
npm install q
